config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'devise/sessions' }
  resources :users
  resources :events
  
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :description, :user_id, presence: true
  belongs_to :user, :studio
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :users, :events

end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :title, :studio, :city, :state, presence: true
  has_many :events
  belongs_to :studio
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Devise shennanigans
  before_action :configure_registration_parameters, if: :devise_controller?

  protected

  def configure_registration_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:first_name, :last_name, :email, :password, :title, :studio, :city, :state)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  # def show
  #   @event =
  # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/form_helper.rb
module FormHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.haml
%h1 All Circus Events
- if @events
  = @events.each do |event|
    %ul
      %li Studio Name: #{}
      %li Address: #{}
        %p #{}, #{}
      %li Description: #{}
  = end
- else
  %p Sorry, there are no events scheduled

app/views/home/index.html.haml
%h1 Welcome to Circus Scheduler
- if current_user
  = link_to 'View My Profile', user_path(:id => current_user.id)
  = link_to 'Logout', destroy_user_session_path, :method => :delete
- else
  = link_to 'Register', new_user_registration_path
  = link_to 'Login', user_session_path

= link_to 'View Events', events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CircusScheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.haml
%h1 #{current_user.first_name}'s profile
%ul
  %li First name: #{current_user.first_name}
  %li Last name: #{current_user.last_name}
  %li Title: #{current_user.title}
  %li Studio: #{}
  %li Location: #{}, #{}

= link_to 'Home', root_url
- if user_signed_in?
  = link_to 'Edit My Profile', edit_user_registration_path